apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  # replicas: 4
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # maxSurge: 8
      maxSurge: 2
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          # image: sweasytech/converter
          image: converter
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
