# From: https://github.com/selikapro/microservices-python/blob/main/src/auth/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  # ClusterIP: => The IP address assigned t the service is only available within our cluster: 
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
