# From: https://github.com/selikapro/microservices-python/blob/main/src/gateway/manifests/configmap.yaml
# Use "ConfigMap" for non-sensitive variables (that are not "secrets")
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
