# From: https://github.com/selikapro/microservices-python/blob/main/src/gateway/manifests/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
stringData:
  PLACEHOLDER: nothing
type: Opaque
