# From: https://github.com/selikapro/microservices-python/blob/main/src/auth/manifests/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_PASSWORD: Auth123
  JWT_SECRET: sarcasm
type: Opaque
