# From: https://github.com/selikapro/microservices-python/blob/main/src/auth/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  # ClusterIP: => The IP address assigned t the service is only available within our cluster:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
