# https://github.com/selikapro/microservices-python/blob/main/src/rabbit/manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      # This port needs an "ingress", to make it accessible from outside the cluster
      # (Since it is the port of the RabbitMQ GUI):
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
